<x-guest-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Publications') }}
        </h2>
    </x-slot>
    <span property="dc:title" content="" class="rdf-meta element-hidden"></span>

    <h3 class="m-0 border border-green-950 bg-slate-400 p-5 w-auto text-xl text-pretty">Journal Papers</h3>
</li>

<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2023</h3>
<ul>
<li class="ml-6 p-3">Blackwell, M., Takahashi, T., Cardenas, L., Collins, A., Enriquez-Hidalgo, D., Griffith, B., Hunt, J., Lee, M.R.F., Misselbrook, T., Neal, A., Rivero, J., Shield, I., Storkey, J., Wu, L., Harris, P. (2023). Potential unintended consequences of agricultural land use change driven by dietary transitions. njp Sustainable Agriculture.</li>
<li class="ml-6 p-3">Cooke, A.S., Mullan, S., Morten, C., Hockenhull, J., Le-Grice, P., Le Cocq, K., Lee, M.R.F., Cardenas, L.M., Rivero, M.J., (2023). Comparison of the welfare of beef cattle in housed and grazing systems: hormones, health and behaviour. The Journal of Agricultural Science, 1-14. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.cambridge.org/core/journals/journal-of-agricultural-science/article/comparison-of-the-welfare-of-beef-cattle-in-housed-and-grazing-systems-hormones-health-and-behaviour/CD3E6155C6650C8DB3EBD773687EE202" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1017/S0021859623000357</a>).</li>
<li class="ml-6 p-3">Crotty, F. V., Demirer, U. A., Norris, S. L., Liu, W. and Murray, P. J. (2023). Evaluating the Impact of Long-Term Land Use Change and Age since Disturbance on Soil Faunal Diversity. Forests,  14, 9,  1882. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.mdpi.com/1999-4907/14/9/1882" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.3390/f14091882</a>).</li>
<li class="ml-6 p-3">Elayadeth-Meethal, M., Jordana Rivero, M., Mead, A., Lee, M., R.F. and Misselbrook, T. H. (2023). Comparison of lipid profiles in the faeces of beef cattle fed three common temperate grass silage diets and their relevance to dietary composition. Journal of Animal and Feed Sciences. (<a class="text-blue-700 hover:text-yellow-700" href="http://www.jafs.com.pl/Comparison-of-lipid-profiles-in-the-faeces-of-beef-cattle-nfed-three-common-temperate,166079,0,2.html" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.22358/jafs/166079/2023</a>).</li>
<li class="ml-6 p-3">Granger, S. J., Upadhayay, H. R. and Collins, A. L. (2023). Hydro-chemical responses at different scales in a rural catchment, UK, and implications for managing the unintended consequences of agriculture. Environmental Research,  228,  115826. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0013935123006187" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.envres.2023.115826</a>).</li>
<li class="ml-6 p-3">Jebari, A., Pereyra-Goday, F., Kumar, A., Collins, A. L., Rivero, M. J. and McAuliffe, G. A. (2023). Feasibility of mitigation measures for agricultural greenhouse gas emissions in the UK. A systematic review. Agronomy for Sustainable Development,  44, 1,  2. (<a class="text-blue-700 hover:text-yellow-700" href="https://link.springer.com/article/10.1007/s13593-023-00938-0#citeas" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1007/s13593-023-00938-0</a>).</li>
<li class="ml-6 p-3">Liu, C., Shan, Y., Wang, Q., Harris, P., Liu, Y. and Wu, L. (2023). Impacts of measured soil hydraulic conductivity on the space–time simulations of water and nitrogen cycling. CATENA,  226,  107058. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0341816223001492" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.catena.2023.107058</a>).</li>
<li class="ml-6 p-3">McAuliffe, G.A., Lynch, J., Cain, M., Buckingham, S., Rees, R.M., Collins, A.L., Allen, M., Pierrehumbert, R., Lee, M.R.F., Takahashi, T., (2023). Are single global warming potential impact assessments adequate for carbon footprints of agri-food systems? Environmental Research Letters 18, 084014. (<a class="text-blue-700 hover:text-yellow-700" href="https://iopscience.iop.org/article/10.1088/1748-9326/ace204" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi 10.1088/1748-9326/ace204</a>).</li>
<li class="ml-6 p-3">Meo-Filho, P., Hood, J., Lee, M. R. F., Fleming, H., Meethal, M. E. and Misselbrook, T. (2023). Performance and enteric methane emissions from housed beef cattle fed silage produced on pastures with different forage profiles. animal,  100726. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S1751731123000228?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.animal.2023.100726</a>).</li>
<li class="ml-6 p-3">Segura, C., Horrocks, C., Lopez-Aizpun, M., Blackwell, M. S. A., Darch, T., Hood, J., Le Cocq, K., McAuliffe, G. A., Lee, M. R. F. and Cardenas, L. (2023). Response of soil health indicators to dung, urine and mineral fertilizer application in temperate pastures. Journal of Environmental Management,  330,  117096. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S030147972202669X?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.jenvman.2022.117096</a>).</li>
<li class="ml-6 p-3">Zhu, S., McCalmont, J., Cardenas, L., Cunliffe, A., Olde, L., Signori Müller, C., Litvak, M., &amp; Hill, T. C. (2023). Gap-filling carbon dioxide, water, energy, and methane fluxes in challenging ecosystems: comparing between methods, drivers, and gap-lengths. Agricultural and Forest Meteorology, 332, 109365. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S016819232300059X?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.agrformet.2023.109365</a>).</li>
<li class="ml-6 p-3">Zhu, S., Olde, L., Lewis, K., Quaife, T., Cardenas, L., Loick, N., Xu, J. and Hill, T. (2023). Eddy covariance fluxes over managed ecosystems extrapolated to field scales at fine spatial resolutions. Agricultural and Forest Meteorology,  342,  109675. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0168192323003659" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: https://doi.org/10.1016/j.agrformet.2023.109675</a>).</li>
</ul>

<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2022</h3>
<ul>
<li class="ml-6 p-3">Angelidis, A. E., McAuliffe, G. A., Takahashi, T., Crompton, L., Yan, T., Reynolds, C. K., Stergiadis, S. and Misselbrook, T. (2022). The Impact of Using Novel Equations to Predict Nitrogen Excretion and Associated Emissions from Pasture-Based Beef Production Systems. Sustainability,  14, 12. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.mdpi.com/2071-1050/14/12/7260/htm">doi: 10.3390/su14127260</a>).</li>
<li class="ml-6 p-3">Cardenas, L. M., Olde, L., Loick, N., Griffith, B., Hill, T., Evans, J., Cowan, N., Segura, C., Sint, H., Harris, P., McCalmont, J., Zhu, S., Dobermann, A. and Lee, M. R. F. (2022). CO2 fluxes from three different temperate grazed pastures using Eddy covariance measurements. Science of The Total Environment,  154819. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S004896972201912X" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: https://doi.org/10.1016/j.scitotenv.2022.154819</a>).</li>
<li class="ml-6 p-3">Cooke, A. S., Le-Grice, P., McAuliffe, G. A., Lee, M. R. F. and Rivero, M. J. (2022). Rethinking efficiency: Growth curves as a proxy for inputs and impacts in finishing beef systems. Journal of Environmental Management,  324,  116418. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0301479722019910?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.jenvman.2022.116418</a>).</li>
<li class="ml-6 p-3">Cooke, A. S., Mullan, S. M., Morten, C., Hockenhull, J., Lee, M. R. F., Cardenas, L. M. and Rivero, M. J. (2022). V-QBA vs. QBA—How Do Video and Live Analysis Compare for Qualitative Behaviour Assessment? Frontiers in Veterinary Science,  9. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.frontiersin.org/articles/10.3389/fvets.2022.832239/full" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.3389/fvets.2022.832239</a>).</li>
<li class="ml-6 p-3">Reay, M. K., Pears, K. A., Kuhl, A., Evershed, R. P., Murray, P. J., Cardenas, L. M., Dungait, J. A. J. and Bull, I. D. (2022). Mechanisms of nitrogen transfer in a model clover-ryegrass pasture: a 15N-tracer approach. Plant and Soil. (<a class="text-blue-700 hover:text-yellow-700" href="https://link.springer.com/article/10.1007/s11104-022-05585-0" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1007/s11104-022-05585-0</a>).</li>
<li class="ml-6 p-3">Upadhayay, H. R., Zhang, Y., Granger, S. J., Micale, M. and Collins, A. L. (2022). Prolonged heavy rainfall and land use drive catchment sediment source dynamics: Appraisal using multiple biotracers. Water Research,  216,  118348. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0043135422003116?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1016/j.watres.2022.118348</a>).</li>
<li class="ml-6 p-3">Zhang, Y., Granger, S. G., Semenov, M. A., Upadhayay, H. R. and Collins, A. L. (2022). Diffuse water pollution during recent extreme wet-weather in the UK: Environmental damage costs and insight into the future? Journal of Cleaner Production,  130633. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0959652622002748?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.jclepro.2022.130633</a>).</li>
<li class="ml-6 p-3">Zhang, Y., Griffith, B., Granger, S., Sint, H. and Collins, A. L. (2022). Tackling unintended consequences of grazing livestock farming: Multi-scale assessment of co-benefits and trade-offs for water pollution mitigation scenarios. Journal of Cleaner Production,  130449. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0959652622000944" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.jclepro.2022.130449</a>).</li>
</ul>
<p></p>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2021</h3>
<ul>
<li class="ml-6 p-3">Castellano-Hinojosa, A., Le Cocq, K., Charteris, A.F., Abadie, M., Chadwick, D.R., Clark, I.M., González-López, J., Bedmar, E.J., Cardenas, L.M. (2021). Relative contributions of bacteria and fungi to nitrous oxide emissions following nitrate application in soils representing different land uses. International Biodeterioration &amp; Biodegradation,  159,  105199. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/abs/pii/S0964830521000299?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.ibiod.2021.105199</a>).</li>
<li class="ml-6 p-3">Charteris, A.F., Harris, P., Marsden, K.A., Harris, I.M., Guo, Z., Beaumont, D.A., Taylor, H., Sanfratello, G., Jones, D.L., Johnson, S.C.M., Whelan, M.J., Howden, N., Sint, H., Chadwick, D.R., Cardenas, L.M. (2021). Within-field spatial variability of greenhouse gas fluxes from an extensive and intensive sheep-grazed agroecosystem. Agriculture, Ecosystems &amp; Environment. 312, p. 107355. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0167880921000591?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.agee.2021.107355</a>).</li>
<li class="ml-6 p-3">Collins, A., Zhang, Y., Upadhayay, H.R., Pulley, S., Granger, S., Harris, P., Sint, H., Griffith B. (2021). Current advisory interventions for grazing ruminant farming cannot close exceedance of modern background sediment loss - assessment using an instrumented farm platform and modelled scaling out. Environmental Science and Policy, 116, 114-127 (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S1462901120313848?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font: inherit; color: rgb(0, 98, 160);">doi.org/10.1016/j.envsci.2020.11.004</a>).</li>
<li class="ml-6 p-3">Curceac, S., Milne, A., Atkinson, P.M., Wu, L., Harris, P. (2021). Elucidating the performance of hybrid models for predicting extreme water flow events through variography and wavelet analyses. Journal of Hydrology,  598,  126442. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.jhydrol.2021.126442" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.jhydrol.2021.126442</a>).</li>
<li class="ml-6 p-3">Jones, A., Takahashi, T., Fleming, H., Griffith, B., Harris, P., Lee, M.R.F. (2021). Quantifying the value of on-farm measurements to inform the selection of key performance indicators for livestock production systems. Scientific Reports, 11,16874. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.nature.com/articles/s41598-021-96336-1" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1038/s41598-021-96336-1</a>).</li>
<li style="margin: 0px 0px 10px 2em; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font: inherit;">Jones, A.G., Takahashi, T., Fleming, H., Griffith, B.A., Harris, P., Lee, M.R.F. (2021). Using a lamb's early-life liveweight as a predictor of carcass quality. Animal. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S1751731120300185" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font: inherit; color: rgb(0, 98, 160);">doi.org/10.1016/j.animal.2020.100018</a>).</li>
<li class="ml-6 p-3">Lee, M.R.F, McAuliffe, G.A., Tweed, J.K.S., Griffith, B.A., Morgan, S.A., Rivero, M.J., Harris, P., Takahashi, T., Cardenas, L. (2021). Nutritional value of suckler beef from temperate pasture systems.Animal,  15, 7,  100257. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S1751731121000999?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.animal.2021.100257</a>).</li>
<li class="ml-6 p-3">Myrgiotis, V., Harris, P., Revill, A., Sint, H., Williams, M. (2021). Inferring management and predicting sub-field scale C dynamics in UK grasslands using biogeochemical modelling and satellite-derived leaf area data. Agricultural and Forest Meteorology.</li>
<li class="ml-6 p-3">Pulley, S., Morten, C., Morgan, S., Cardenas, L. M. and Collins, A. L. (2021). Sediment detachment by raindrop impact on grassland and arable fields: an investigation of controls. Journal of Soils and Sediments. (<a class="text-blue-700 hover:text-yellow-700" href="https://link.springer.com/article/10.1007/s11368-021-03098-4" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1007/s11368-021-03098-4</a>).</li>
<li class="ml-6 p-3">Pulley, S., Cardenas, L.M., Grau, P., Mullan, S., Rivero, M. J. and Collins, A. L. (2021). Does cattle and sheep grazing under best management significantly elevate sediment losses? Evidence from the North Wyke Farm Platform, UK. Journal of Soils and Sediments. (<a class="text-blue-700 hover:text-yellow-700" href="https://link.springer.com/article/10.1007/s11368-021-02909-y" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1007/s11368-021-02909-y</a>).</li>
<li class="ml-6 p-3">Rivero, M. J., Evans, A. C. O., Berndt, A., Cartmill, A., Dowsey, A., Farruggia, A., Mignolet, C., Enriquez-Hidalgo, D., Chadwick, D., McCracken, D. I., Busch, D., Pereyra, F., Martin, G. B., Sanford, G. R., Sheridan, H., Wright, I., Brunet, L., Eisler, M. C., Lopez-Villalobos, N., Rovira, P., Harris, P., Murphy, P., Williams, A. P., Jackson, R. D., Machado, R., P.T., S., Puech, T., Boland, T. M., Ayala, W. and Lee, M. R. F. (2021). Taking the steps toward sustainable livestock: our multidisciplinary global farm platform journey. Animal Frontiers,  11, 5,  52-58. (<a class="text-blue-700 hover:text-yellow-700" href="https://academic.oup.com/af/article/11/5/52/6404330" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1093/af/vfab048</a>).</li>
<li class="ml-6 p-3">Rivero, M.J., Lopez-Villalobos, N., Evans, A., Berndt, A., Cartmill, A., Neal, A., McLaren, A., Farruggia, A., Mignolet, C., Durant, D., Chadwick, D., Styles, D., McCraken, D., Busch, D., Martin, G., Fleming, H., Sheridan, H., Gibbons, J., Merbold, L.,  Eisler, M., Lambe, N., Rovira, P., Harris, P., Murphy,P., Williams, P., Machado, R., Takahashi, T., Puech, T., Boland, T., Ayala, W., Lee, M.R.F. (2021). Key traits for ruminant livestock across diverse production systems in the context of climate change: perspectives from a global platform of research farms. Reproduction, Fertility and Development, 33, 2,1-19. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.publish.csiro.au/rd/RD20205" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1071/RD20205</a>).</li>
<li class="ml-6 p-3">Thomas, C.L., Darch, T., Harris, P., Beaumont, D.A., Haefele, S.M. (in press). The distribution of soil micro-nutrients and the effects on herbage micro-nutrient uptake and yield in three different pasture systems. Agronomy,  11, 9,  1731. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.mdpi.com/2073-4395/11/9/1731" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.3390/agronomy11091731</a>).</li>
<li class="ml-6 p-3">Upadhayay, H.R., Granger, S.J., Zhang, Y., Amorim, F., Cilione, L., Micale, M. and Collins, A.L. (2021). Insights into bulk stable isotope alteration during sediment redistribution to edge-of-field: impact on sediment source apportionment. Biogeochemistry. (<a class="text-blue-700 hover:text-yellow-700" href="https://link.springer.com/article/10.1007/s10533-021-00825-4" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1007/s10533-021-00825-4</a>).</li>
<li class="ml-6 p-3">Wu, L., Harris, P., Misselbrook, T., Lee, M.R.F. (2021). Simulating grazing beef and sheep systems. Agricultural Systems,195. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0308521X21002602" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.agsy.2021.103307</a>).</li>
<li class="ml-6 p-3">Wu, L., Curceac, S., Atkinson, P.M., Milne, A., Harris, P. (2021). A case study on the effects of data temporal resolution on the simulation of water flux extremes using a process-based model at the grassland field scale. Agricultural Water Management, 255. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0378377421003140" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.1016/j.agwat.2021.107049</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2020</h3>
<ul>
<li class="ml-6 p-3">Curceac, S., Atkinson, P. M., Milne, A., Wu, L. and Harris, P. (2020). Adjusting for conditional bias in process model simulations of hydrological extremes: an experiment using the North Wyke Farm Platform. Frontiers in Artificial Intelligence – Special Issue on Machine Learning for Water Resources, 3, 82, 565859. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.frontiersin.org/articles/10.3389/frai.2020.565859/full?&amp;utm_source=Email_to_authors_&amp;utm_medium=Email&amp;utm_content=T1_11.5e1_author&amp;utm_campaign=Email_publication&amp;field=&amp;journalName=Frontiers_in_Artificial_Intelligence&amp;id=565859" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.3389/frai.2020.565859</a>).</li>
<li class="ml-6 p-3">Curceac, S., Atkinson, P. M., Milne, A., Wu, L. and Harris, P. (2020). An evaluation of automated GPD threshold selection methods for hydrological extremes across different scales. Journal of Hydrology,  585,  124845. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S002216942030305X" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: https://doi.org/10.1016/j.jhydrol.2020.124845</a>).</li>
<li class="ml-6 p-3">McAuliffe, G. A., López-Aizpún, M., Blackwell, M. S. A., Castellano-Hinojosa, A., Darch, T., Evans, J., Horrocks, C., Le Cocq, K., Takahashi, T., Harris, P., Lee, M. R. F. and Cardenas, L. (2020). Elucidating three-way interactions between soil, pasture and animals that regulate nitrous oxide emissions from temperate grazing systems. Agriculture, Ecosystems &amp; Environment,  300,  106978. (doi: <a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.agee.2020.106978" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">https://doi.org/10.1016/j.agee.2020.106978</a>).</li>
<li class="ml-6 p-3">McDermott, K., Lee, M. R. F., McDowall, K. J. and Greathead, H. M. R. (2020). Cross Inoculation of Rumen Fluid to Improve Dry Matter Disappearance and Its Effect on Bacterial Composition Using an in vitro Batch Culture Model. Frontiers in Microbiology,  11, 2293. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.frontiersin.org/articles/10.3389/fmicb.2020.531404/full?&amp;utm_source=Email_to_authors_&amp;utm_medium=Email&amp;utm_content=T1_11.5e1_author&amp;utm_campaign=Email_publication&amp;field=&amp;journalName=Frontiers_in_Microbiology&amp;id=531404" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.3389/fmicb.2020.531404</a>).</li>
<li class="ml-6 p-3">Pulley, S. and Collins, A. L. (2020). Sediment loss in response to scheduled pasture ploughing and reseeding: The importance of soil moisture content in controlling risk. Soil and Tillage Research,  204,  104746. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0167198720305286?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: https://doi.org/10.1016/j.still.2020.104746</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2019</h3>
<ul>
<li class="ml-6 p-3">Carswell, A. M., Gongadze, K., Misselbrook, T. H. and Wu, L. (2019). Impact of transition from permanent pasture to new swards on the nitrogen use efficiency, nitrogen and carbon budgets of beef and sheep production. Agriculture, Ecosystems &amp; Environment, 283, 106572. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.agee.2019.106572" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.agee.2019.106572</a>).</li>
<li class="ml-6 p-3">Collins, A. L., Burak, E., Harris, P., Pulley, S., Cardenas, L. and Tang, Q. (2019). Field scale temporal and spatial variability of δ13C, δ15N, TC and TN soil properties: Implications for sediment source tracing. Geoderma, 333, 108-122. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.geoderma.2018.07.019" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.geoderma.2018.07.019</a>).</li>
<li class="ml-6 p-3">Cooke, A. S., Watt, K. A., Morgan, E. R. and Dungait, J. A. J. (2019). The latest FAD – Faecal antibody detection in cattle. Protocol and results from three UK beef farms naturally infected with gastrointestinal nematodes. Parasitology, 146, 1, 89-96. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.cambridge.org/core/journals/parasitology/article/latest-fad-faecal-antibody-detection-in-cattle-protocol-and-results-from-three-uk-beef-farms-naturally-infected-with-gastrointestinal-nematodes/700C9216EB959E50FA724455C26E5743" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1017/S0031182018000902</a>).</li>
<li class="ml-6 p-3">Johnston, A. E. and Poulton, P. R. (2019). Phosphorus in Agriculture: A Review of Results from 175 Years of Research at Rothamsted, UK. Journal of Environmental Quality,  48, 5,  1133-1144. (<a class="text-blue-700 hover:text-yellow-700" href="https://acsess.onlinelibrary.wiley.com/doi/abs/10.2134/jeq2019.02.0078" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.2134/jeq2019.02.0078</a>).</li>
<li class="ml-6 p-3">Orr, R. J., Griffith, B. A., Rivero, M. J. and Lee, M. R. F. (2019). Livestock Performance for Sheep and Cattle Grazing Lowland Permanent Pasture: Benchmarking Potential of Forage-Based Systems. 9, 2, 101-118. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.mdpi.com/2073-4395/9/2/101" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.3390/agronomy9020101</a>).</li>
<li class="ml-6 p-3">Pulley, S. and Collins, A. L. (2019). Field-based determination of controls on runoff and fine sediment generation from lowland grazing livestock fields. Journal of Environmental Management, 249, 109365. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.jenvman.2019.109365" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.jenvman.2019.109365</a>).</li>
<li class="ml-6 p-3">Shepherd, A., Hartman, M. D., Fitton, N., Horrocks, C. A., Dunn, R. M., Hastings, A. and Cardenas, L. M. (2019). Metrics of biomass, live-weight gain and nitrogen loss of ryegrass sheep pasture in the 21st century. Science of The Total Environment. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.scitotenv.2019.05.038" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.scitotenv.2019.05.038</a>).</li>
<li class="ml-6 p-3">Thomas, A. C., Bailey, M., Lee, M. R. F., Mead, A., Morales-Aza, B., Reynolds, R., Vipond, B., Finn, A. and Eisler, M. C. (2019). Insights into Pasteurellaceae carriage dynamics in the nasal passages of healthy beef calves. Scientific Reports, 9, 1, 11943. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.nature.com/articles/s41598-019-48007-5" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1038/s41598-019-48007-5</a>).</li>
<li class="ml-6 p-3">Wang, J. (2019). Effects of Grazing Management on Spatio-Temporal Heterogeneity of Soil Carbon and Greenhouse Gas Emissions of Grasslands and Rangelands: Monitoring, Modelling and Upscaling. Preprints,  2019070003 (<a class="text-blue-700 hover:text-yellow-700" href="https://www.preprints.org/manuscript/201907.0003/v1" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.20944/preprints201907.0003.v1</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2018</h3>
<ul>
<li class="ml-6 p-3">Blackwell, M. S. A., Jarvis, S. C., Wilkins, R. J., Beaumont, D. A., Cardenas, L. M., Chadwick, D. R., Collins, A. L., Dungait, J. A. J., Gibb, M. J., Hopkins, A., Lee, M. R. F., Misselbrook, T. H., Murray, P. J. and Tallowin, J. R. B. (2018). The Importance of Sustained Grassland and Environmental Research: A Case Study From North Wyke Research Station, UK, 1982–2017. Advances in Agronomy, Academic Press (<a class="text-blue-700 hover:text-yellow-700" href="https://research-information.bristol.ac.uk/en/publications/the-importance-of-sustained-grassland-and-environmental-research(7dd5c799-88ab-414e-9c60-ddcda748059b)/export.html" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/bs.agron.2018.01.004</a>).</li>
<li class="ml-6 p-3">Eludoyin, A. O. and Ibitoye, M. O. (2018). Relationship between precipitation and soil water chemistry in an intensively managed clayey soil environment in southwest England: a preliminary study. International Journal of Hydrology Science and Technology, 8, 8, 339-351. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.inderscience.com/info/inarticle.php?artid=95535" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1504/IJHST.2018.095535</a>).</li>
<li class="ml-6 p-3">Granger, S. J., Yang, Y., Pfahler, V., Hodgson, C., Smith, A. C., Le Cocq, K., Collins, A. L., Blackwell, M. S. A. and Howden, N. J. K. (2018). The stable oxygen isotope ratio of resin extractable phosphate derived from fresh cattle faeces. Rapid Communications in Mass Spectrometry, 32, 9, 703-710. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/full/10.1002/rcm.8092" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1002/rcm.8092</a>).</li>
<li class="ml-6 p-3">Kendall, I. P., Lee, M. R. F. and Evershed, R. P. (2018). The effect of trophic level on individual amino acid δ15N values in a terrestrial ruminant food web. STAR: Science &amp; Technology of Archaeological Research, 1-12. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.tandfonline.com/doi/full/10.1080/20548923.2018.1459361" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1080/20548923.2018.1459361</a>).</li>
<li class="ml-6 p-3">Liu, Y., Li, Y., Harris, P., Cardenas, L. M., Dunn, R. M., Sint, H., Murray, P. J., Lee, M. R. F. and Wu, L. (2018). Modelling field scale spatial variation in water run-off, soil moisture, N2O emissions and herbage biomass of a grazed pasture using the SPACSYS model. Geoderma, 315, 49-58. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.geoderma.2017.11.029">doi:10.1016/j.geoderma.2017.11.029</a>).</li>
<li class="ml-6 p-3">McAuliffe, G. A., Takahashi, T., Orr, R. J., Harris, P. and Lee, M. R. F. (2018). Distributions of emissions intensity for individual beef cattle reared on pasture-based production systems. Journal of Cleaner Production, 171, 1672-1680. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.sciencedirect.com/science/article/pii/S0959652617324125?via%3Dihub" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.jclepro.2017.10.113</a>).</li>
<li class="ml-6 p-3">Takahashi, T., Harris, P., Blackwell, M. S. A., Cardenas, L. M., Collins, A. L., Dungait, J. A. J., Hawkins, J. M. B., Misselbrook, T. H., McAuliffe, G. A., McFadzean, J. N., Murray, P. J., Orr, R. J., Rivero, M. J., Wu, L. and Lee, M. R. F. (2018). Roles of instrumented farm-scale trials in trade-off assessments of pasture-based ruminant production systems. Animal, 12, 8, 1766-1776. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.cambridge.org/core/journals/animal/article/roles-of-instrumented-farmscale-trials-in-tradeoff-assessments-of-pasturebased-ruminant-production-systems/E1F8FC3C9934F6F5ADC0605B7E393FFE" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1017/S1751731118000502</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2017</h3>
<ul>
<li class="ml-6 p-3">Benefer, C. M., D'Ahmed, K. S., Murray, P. J. and Blackshaw, R. P. (2017). Molecular identification and distribution of leatherjackets (Diptera: Tipulidae) in U.K. agricultural grassland. Agricultural and Forest Entomology, 19, 4, 400-407. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/abs/10.1111/afe.12219" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1111/afe.12219</a>).</li>
<li class="ml-6 p-3">Coleman, K., Muhammed, S. E., Milne, A. E., Todman, L. C., Dailey, A. G., Glendining, M. J. and Whitmore, A. P. (2017). The landscape model: A model for exploring trade-offs between agricultural production and the environment. Science of The Total Environment, 609, Supplement C, 1483-1499. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.scitotenv.2017.07.193" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.scitotenv.2017.07.193</a>).</li>
<li class="ml-6 p-3">Eludoyin, A. O., Griffith, B., Orr, R. J., Bol, R., Quine, T. A. and Brazier, R. E. (2017). An evaluation of the hysteresis in chemical concentration–discharge (C–Q) relationships from drained, intensively managed grasslands in southwest England. Hydrological Sciences Journal, 62, 8, 1243-1254. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.tandfonline.com/doi/abs/10.1080/02626667.2017.1313979?journalCode=thsj20" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1080/02626667.2017.1313979</a>).</li>
<li class="ml-6 p-3">Evans, R., Collins, A. L., Zhang, Y., Foster, I. D. L., Boardman, J., Sint, H., Lee, M. R. F. and Griffith, B. A. (2017). A comparison of conventional and 137Cs-based estimates of soil erosion rates on arable and grassland across lowland England and Wales. Earth-Science Reviews, 173, Supplement C, 49-64. (<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.earscirev.2017.08.005" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.earscirev.2017.08.005</a>).</li>
<li class="ml-6 p-3">Granger, S. J., Harris, P., Peukert, S., Guo, R., Tamburini, F., Blackwell, M. S. A., Howden, N. J. K. and McGrath, S. (2017). Phosphate stable oxygen isotope variability within a temperate agricultural soil. Geoderma, 285, 64-75. (doi:<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.geoderma.2016.09.020" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">10.1016/j.geoderma.2016.09.020</a>).</li>
<li class="ml-6 p-3">Li, Y., Liu, Y., Harris, P., Sint, H., Murray, P. J., Lee, M. R. F. and Wu, L. (2017). Assessment of soil water, carbon and nitrogen cycling in reseeded grassland on the North Wyke Farm Platform using a process-based model. Science of The Total Environment, 603, Supplement C, 27-37. (doi:<a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.1016/j.scitotenv.2017.06.012" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">10.1016/j.scitotenv.2017.06.012</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2016</h3>
<ul>
<li class="ml-6 p-3">Benefer, C. M., D'Ahmed, K. S., Blackshaw, R. P., Sint, H. M. and Murray, P. J. (2016). The Distribution of Soil Insects across Three Spatial Scales in Agricultural Grassland. Frontiers in Ecology and Evolution, 4, 41. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.frontiersin.org/articles/10.3389/fevo.2016.00041/full" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.3389/fevo.2016.00041</a>).</li>
<li class="ml-6 p-3">Cardenas, L. M., Collins, A. L., Dungait, J. A. J., Hawkins, J., Chabbi, A. and Hawes, C. (2016). The contribution of farm-scale experiments to the understanding of soil processes and implications for ecosystem services. European Journal of Soil Science, 67, 4, 359-359. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/full/10.1111/ejss.12360" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1111/ejss.12360</a>).</li>
<li class="ml-6 p-3">Goulding, K. W. T. (2016). Soil acidification and the importance of liming agricultural soils with particular reference to the United Kingdom. Soil Use and Management,  32, 3,  390-399. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/full/10.1111/sum.12270" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.1111/sum.12270</a>).</li>
<li class="ml-6 p-3">Liu, W., Zhang, J., Norris, S. L. and Murray, P. J. (2016). Impact of Grassland Reseeding, Herbicide Spraying and Ploughing on Diversity and Abundance of Soil Arthropods. Frontiers in Plant Science, 7, 1200. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.frontiersin.org/articles/10.3389/fpls.2016.01200/full" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.3389/fpls.2016.01200</a>).</li>
<li class="ml-6 p-3">Orr, R. J., Murray, P. J., Eyles, C. J., Blackwell, M. S. A., Cardenas, L. M., Collins, A. L., Dungait, J. A. J., Goulding, K. W. T., Griffith, B. A., Gurr, S. J., Harris, P., Hawkins, J. M. B., Misselbrook, T. H., Rawlings, C., Shepherd, A., Sint, H., Takahashi, T., Tozer, K. N., Whitmore, A. P., Wu, L. and Lee, M. R. F. (2016). The North Wyke Farm Platform: effect of temperate grassland farming systems on soil moisture contents, runoff and associated water quality dynamics. European Journal of Soil Science, 67, 4, 374-385. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/10.1111/ejss.12350" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1111/ejss.12350</a>).</li>
<li class="ml-6 p-3">Peukert, S., Griffith, B. A., Murray, P. J., Macleod, C. J. A. and Brazier, R. E. (2016). Spatial variation in soil properties and diffuse losses between and within grassland fields with similar short-term management. European Journal of Soil Science, 67, 4, 386-396. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/full/10.1111/ejss.12351" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1111/ejss.12351</a>).</li>
<li class="ml-6 p-3">Shepherd, A., Atuhaire, W., Wu, L., Hogan, D., Dunn, R. and Cardenas, L. (2016). Historic record of pasture soil water and the influence of the North Atlantic Oscillation in south-west England. Hydrology Research, 48, 1, 277-294. (<a class="text-blue-700 hover:text-yellow-700" href="https://iwaponline.com/hr/article/48/1/277/1702/Historic-record-of-pasture-soil-water-and-the" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.2166/nh.2016.195</a>).</li>
<li class="ml-6 p-3">Wu, L., Zhang, X., Griffith, B. A. and Misselbrook, T. H. (2016). Sustainable grassland systems: a modelling perspective based on the North Wyke Farm Platform. European Journal of Soil Science, 67, 4, 397-408. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/10.1111/ejss.12304" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1111/ejss.12304</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2014</h3>
<ul>
<li class="ml-6 p-3">Eisler, M. C., Lee, M. R. F., Tarlton, J. F., Martin, G. B., Beddington, J., Dungait, J. A. J., Greathead, H., Liu, J., Mathew, S., Miller, H., Misselbrook, T., Murray, P., Vinod, V. K., Van Saun, R. and Winter, M. (2014). Agriculture: Steps to sustainable livestock. Nature, 507, 7490, 32-34. (<a class="text-blue-700 hover:text-yellow-700" href="https://www.nature.com/news/agriculture-steps-to-sustainable-livestock-1.14796" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1038/507032a</a>).</li>
<li class="ml-6 p-3">Peukert, S., Griffith, B. A., Murray, P. J., Macleod, C. J. A. and Brazier, R. E. (2014). Intensive Management in Grasslands Causes Diffuse Water Pollution at the Farm Scale. Journal of Environmental Quality, 43, 6, 2009-2023. (<a class="text-blue-700 hover:text-yellow-700" href="https://dl.sciencesocieties.org/publications/jeq/abstracts/43/6/2009" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.2134/jeq2014.04.0193</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2012</h3>
<ul>
<li class="ml-6 p-3">Peukert, S., Bol, R., Roberts, W., Macleod, C. J. A., Murray, P. J., Dixon, E. R. and Brazier, R. E. (2012). Understanding spatial variability of soil properties: a key step in establishing field- to farm-scale agro-ecosystem experiments. Rapid Communications in Mass Spectrometry, 26, 20, 2413-2421. (<a class="text-blue-700 hover:text-yellow-700" href="https://onlinelibrary.wiley.com/doi/abs/10.1002/rcm.6336" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1002/rcm.6336</a>).</li>
</ul>
<pre>
</pre>
<li>
    <h3 class="m-0 border border-green-950 bg-slate-400 p-5 w-auto text-xl text-pretty">Data Journal Papers</h3>
</li>

<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2024</h3>
<ul>
<li class="ml-6 p-3">Cooke, A., Morten, C., Le-Grice, P., Hockenhull, J., Griffith, B. A., Mullan, S. M., Lee, M. R. F., Cardenas, L. M. and Rivero, M. J. (2024). Comparison of in-person qualitative behaviour assessment (QBA) and video qualitative behaviour assessments (V-QBA) of beef cattle. Rothamsted Research. <a class="text-blue-700 hover:text-yellow-700" href="https://repository.rothamsted.ac.uk/item/99027/comparison-of-in-person-qualitative-behaviour-assessment-qba-and-video-qualitative-behaviour-assessments-v-qba-of-beef-cattle" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">https://doi.org/10.23637/rothamsted.99027</a>.</li>
<li class="ml-6 p-3">Cooke, A., Morten, C., Le-Grice, P., Hockenhull, J., Griffith, B. A., Mullan, S. M., Le Cocq, K., Lee, M. R. F., Cardenas, L. M. and Rivero, M. J. (2024). Comparison of the welfare of beef cattle in housed and grazing systems: hormones, health and behaviour. Rothamsted Research. <a class="text-blue-700 hover:text-yellow-700" href="https://repository.rothamsted.ac.uk/item/99028/comparison-of-the-welfare-of-beef-cattle-in-housed-and-grazing-systems-hormones-health-and-behaviour" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">https://doi.org/10.23637/rothamsted.99028</a>.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2023</h3>
<ul>
<li class="ml-6 p-3">Beaumont, D. A., Taylor, H., Griffith, B. A., Morten, C., Hunt, J., Retter, A., Bearder, T., Dungait, J. A. J., Murray, P. J. and Blackwell, M. S. A. (2023). A 4-year comparison of pasture mixtures, including those with deep-rooting Festulolium, on herbage and soil and root properties in 50 cm cores, plus associated botanical species surveys. Rothamsted Research. <a class="text-blue-700 hover:text-yellow-700" href="https://repository.rothamsted.ac.uk/item/98y26/a-4-year-comparison-of-pasture-mixtures-including-those-with-deep-rooting-festulolium-on-herbage-and-soil-and-root-properties-in-50-cm-cores-plus-associated-botanical-species-surveys" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">https://doi.org/10.23637/rothamsted.98y26</a>.</li>
<li class="ml-6 p-3">Darch, T., McAuliffe, G., Le Cocq, K., Horrocks, C. A., Segura, C., Griffith, B. A., Harris, P., Hood, J., Joynes, A., Lopez, M., Takahashi, T., Lee, M. R. F. and Cardenas, L. M. (2023). Effect of pasture composition in cattle grazed systems on soil properties and nutrient cycling: impact on herbage, soil and cattle excreta. Rothamsted Research. (<a class="text-blue-700 hover:text-yellow-700" href="https://repository.rothamsted.ac.uk/item/98x4z/effect-of-pasture-composition-in-cattle-grazed-systems-on-soil-properties-and-nutrient-cycling-impact-on-herbage-soil-and-cattle-excreta" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.23637/rothamsted.98x4z</a>).</li>
<li class="ml-6 p-3">Granger, S. J., Quincke, J. A., Carswell, A. M., Olde, L., Darch, T., Peukert, S., Horrocks, C. A., Dixon, E. R., Collins, A. L., Blackwell, M. S. A., Murray, P. J., Dungait, J. A. J. and Harris, P. (2023). Water chemistry of combined surface and subsurface runoff from the North Wyke Farm Platform, with hydrologically isolated catchments sown with different pasture types. Rothamsted Research. (<a class="text-blue-700 hover:text-yellow-700" href="https://repository.rothamsted.ac.uk/item/98v27/water-chemistry-of-combined-surface-and-subsurface-runoff-from-the-north-wyke-farm-platform-with-hydrologically-isolated-catchments-sown-with-different-pasture-types" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.23637/rothamsted.98v27</a>).</li>
<li class="ml-6 p-3">Segura, C., Neal, A. L., Castro-Sardina, L. and Irisarri, G. (2023). Field features of the North Wyke Farm Platform: weather, topography, soil, ecosystem services provision index and management . Rothamsted Research. <a class="text-blue-700 hover:text-yellow-700" href="https://repository.rothamsted.ac.uk/item/98y60/field-features-of-the-north-wyke-farm-platform-weather-topography-soil-ecosystem-services-provision-index-and-management" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">https://doi.org/10.23637/rothamsted.98y60</a>.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2022</h3>
<ul>
<li class="ml-6 p-3">Charteris, A.F., Harris, P.,  Marsden, K.A., Harris, I.M., Guo, Z.; Beaumont, D.A., Taylor, H., Sanfratello, G., Jones, D.L., Johnson, S.C.M., Whelan, M.J., Howden, N., Sint, H., Chadwick, D.R., Cárdenas, L.M. (2022). Single time point sampling of site characteristics, soil parameters and soil greenhouse gas emissions for extensive and intensive sheep-farming sites in North Wales and Devon, 2016. NERC EDS Environmental Information Data Centre. (Dataset). (<a class="text-blue-700 hover:text-yellow-700" href="https://catalogue.ceh.ac.uk/documents/f3118fa8-6bec-488b-9713-2415912b8b9e">doi.org/10.5285/f3118fa8-6bec-488b-9713-2415912b8b9e</a>).</li>
<li class="ml-6 p-3">Granger, S. J., Olde, L., Hodgson, C. J., Blackwell, M. S. A., Sint, H. M., Quincke, J. A. and Harris, P. (2022). Water chemistry under low-flow conditions from grazed pastures seeded with different species. Rothamsted Research. (<a class="text-blue-700 hover:text-yellow-700" href="https://repository.rothamsted.ac.uk/item/98q74/water-chemistry-under-low-flow-conditions-from-grazed-pastures-seeded-with-different-species" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi.org/10.23637/rothamsted.98q74</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2021</h3>
<ul>
<li class="ml-6 p-3">Jones, A., Fleming, H., Griffith, B., Takahashi, T., Lee, M., Harris, P. (2021). Data to identify key drivers of animal growth and carcass quality for temperate lowland sheep production systems. Accepted Data in Brief.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2020</h3>
<ul>
<li class="ml-6 p-3">Hodgson, C.J. (2020). Antibiotic resistant gene abundance in fresh cattle faeces from the North Wyke Farm Platform. NERC Environmental Information Data Centre. (Dataset). (<a class="text-blue-700 hover:text-yellow-700" href="https://catalogue.ceh.ac.uk/documents/efcef5e3-09f2-4a23-ad19-53295a3171ce">doi.org/10.5285/efcef5e3-09f2-4a23-ad19-53295a3171ce</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2019</h3>
<ul>
<li class="ml-6 p-3">Hodgson, C. J. (2019). E. coli counts of fresh cattle faeces from the North Wyke Farm Platform. NERC Environmental Information Data Centre. (Dataset). (<a class="text-blue-700 hover:text-yellow-700" href="https://catalogue.ceh.ac.uk/documents/ec83a4ea-923a-4f02-8a9f-aeecc43d7123">doi.org/10.5285/ec83a4ea-923a-4f02-8a9f-aeecc43d7123</a>).</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2018</h3>
<ul>
<li class="ml-6 p-3">McAuliffe, G. A., Takahashi, T., Orr, R. J., Harris, P. and Lee, M. R. F. (2018). Data to calculate emissions intensity for individual beef cattle reared on pasture-based production systems. Data in Brief, 17, 570-574. (<a class="text-blue-700 hover:text-yellow-700" href="https://pubmed.ncbi.nlm.nih.gov/29552605/" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1016/j.dib.2018.01.075</a>).</li>
</ul>

<li>
    <h3 class="m-0 border border-green-950 bg-slate-400 p-5 w-auto text-xl text-pretty">Conference Papers</h3>
</li>

<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2023</h3>
<ul>
<li class="ml-6 p-3">Comber, A. and Harris, P. (2023). Geosensor Network Optimisation to Support Decisions at Multiple Scales. Web and Wireless Geographical Information Systems, Cham, Springer Nature Switzerland. (<a class="text-blue-700 hover:text-yellow-700" href="https://link.springer.com/chapter/10.1007/978-3-031-34612-5_1#citeas" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi:10.1007/978-3-031-34612-5_1</a>)</li>
</ul>
<p></p>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2022</h3>
<ul>
<li class="ml-6 p-3">Harris P. (2022). Ag Digital Twins based on the North Wyke Farm Platform ‘farm lab’ – AgriTech East, Harpenden, UK, 2022.</li>
<li class="ml-6 p-3">Harris P., Baker C., Blackwell M., Metcalfe H., Willcock S., Wu L., Collins A. (2022). Digital Twins in Agriculture: a route map for deployment at the whole farm scale. Tipping Points from climate crisis to positive transformation, University of Exeter, UK.</li>
<li class="ml-6 p-3">Harris P., Baker C., Blackwell M., Metcalfe H., Willcock S., Wu L., Collins A. (2022). Digital Twins in Agriculture: challenges for their deployment at the whole farm scale. NERC CDE22 – Constructing a Digital Environment Conference, Birmingham, UK.</li>
<li class="ml-6 p-3">Harris P. (2022). Digital Twins in Agriculture: implementation challenges for the North Wyke Farm Platform. 2nd international workshop on Environment-Driven Requirements Engineering (EnviRE) for software systems, Melbourne, Australia, 2022 (conference keynote)</li>
<li class="ml-6 p-3">de Mio Filho, P. et al. (2022). Pasture Type under Continuous Stocking Had No Effect on Beef Cattle Performance or Enteric Methane Emissions. Greenhouse Gas and Animal Agriculture (GGAA) conference, June 5-9 2022, Orlando, Florida, USA.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2021</h3>
<ul>
<li class="ml-6 p-3">Cardenas L. (2021). Hackathon Impact lab: Overview of Air quality from Agriculture, Achieving Net Zero Farming Target- Air Quality, <a class="text-blue-700 hover:text-yellow-700" href="https://www.youtube.com/watch?v=qY9RJK3sNU4" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">Online Hackathon</a>.</li>
<li class="ml-6 p-3">Cardenas L. (2021). Net Zero Farming Forum-workshop 3: Impact of land management on GHG emissions,webinar.</li>
<li class="ml-6 p-3">Collins A. (2021). Footprinting and benchmarking your farm to support decision making for sustainability: lecture presented to WWF and Tesco agricultural team, May 2021.</li>
<li class="ml-6 p-3">Harris P. (2021). The North Wyke Farm Platform. Dookie College, University of Melbourne Australia, webinar.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2020</h3>
<ul>
<li class="ml-6 p-3">Harris P. (2020). The North Wyke Farm Platform. UK-India Agri-innovation linkup FCDO webinar. </li>
<li class="ml-6 p-3">Harris P. (2020). The North Wyke Farm Platform. University of Leeds webinar.</li>
<li class="ml-6 p-3">Mahmood K., Harris P., Wu L., Curceac S. (2020). Digital Agri &amp; Environmental Solutions: SME collaborations. <a class="text-blue-700 hover:text-yellow-700" href="https://www.youtube.com/watch?v=8ojCdGm4pW8" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">ERDF Impact Lab webinar</a>.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2019</h3>
<ul>
<li class="ml-6 p-3">Blackwell M.S.A, (2019). Nutrient efficiency and improving the nutritional value of crops: innovations from the UK. 2<sup>nd</sup> International Workshop on Agriculture Green Development, China Agricultural University, Beijing. 12<font size="1">-</font>16<sup>th</sup> October 2019.</li>
<li class="ml-6 p-3">Blackwell M.S.A, (2019). Phosphorus Fertilizer management: developments in the UK. Global Phosphate and Compound Fertiliser Industry Development Conference, Shangri-la Hotel, Beijing 28<font size="1">-</font>29<sup>th</sup> August 2019.</li>
<li class="ml-6 p-3">Christou A., Fleming H., Hodgson C., Cogan T., Gaffney M., Davies D., Lee M.R.F. (2019). Impact of bio-stimulants on ryegrass silage quality, aerobic stability and animal performance. British Society of Animal Science, Edinburgh, April 2019, pp 109.</li>
<li class="ml-6 p-3">Collins A.L., Zhang Y., Pulley S., Upadhayay H. (2019) Field scale spatial variability in tracer properties: implications for sediment source fingerprinting. In session: Using fingerprinting and modelling techniques to explore transfer and connectivity in catchment sediment systems, <a class="text-blue-700 hover:text-yellow-700" href="http://www.iugg2019montreal.com/" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">27<sup>th</sup> IUGG General Assembly, Montreal, Canada, July 2019. </a></li>
<li class="ml-6 p-3">Collins A.L., Zhang Y., Pulley S., Upadhayay H.R. (2019) Can the sediment pollution gap from intensive livestock farming be closed? Assessment using the North Wyke Farm Platform, UK. In session: Land degradation due to natural and anthropogenic drivers: impacts on runoff, soil erosion and sediment yield at multiple scales, <a class="text-blue-700 hover:text-yellow-700" href="http://www.iugg2019montreal.com/" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">27<sup>th</sup> IUGG General Assembly, Montreal, Canada, July 2019.</a></li>
<li class="ml-6 p-3">Collins A.L., Zhang Y., Pulley S., Upadhayay H.R. (2019) Invited Keynote: Can the sediment pollution gap from intensive livestock farming be closed? Assessment using the North Wyke Farm Platform. <a class="text-blue-700 hover:text-yellow-700" href="https://www.teagasc.ie/publications/2019/catchment-science-2019.php" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">Catchment Science 2019: Achieving quality water in diverse and productive agricultural landscapes under a changing climate, Wexford, Ireland, November 2019.</a></li>
<li class="ml-6 p-3">Cooke A., McAuliffe G.A., Takahashi T., Lee M.R.F., Rivero J. (2019). Field to yield: improving our assessment of livestock value on farm and beyond. British Society of Animal Science, Edinburgh, April 2019, pp 201.</li>
<li class="ml-6 p-3">Curceac S., Atkinson P.M., Milne A., Wu L., Harris P., (2019). Applying a combined deterministic and probabilistic modelling framework for improved simulation of hydrological extremes in a grassland context. EVAN, Paris, 2019.</li>
<li class="ml-6 p-3">Curceac S., Atkinson P.M., Milne A., Wu L., Harris P., (2019). Improved characterisation of extreme water flow events in a grassland context using a combined mechanistic and probabilistic modelling framework. 7<sup>th</sup> CNC, Harpenden, 2019.</li>
<li class="ml-6 p-3">Elayadeth-Meethal M., Misselbrook T.H., Fleming H.R., Evans J., Rivero J.M. Lee M.R.F. (2019). Circadian rhythm in enteric methane emission among temperate grassland beef cattle offered three typical grass silage diets. European Federation of Animal Science, Ghent, Belgium, August 2019, pp 84.</li>
<li class="ml-6 p-3">Evans J., Cardenas L., Dunn R.M., Brocolo F., Griffith B., Harris P., Orr R., Loick N., Olde L., Misselbrook T., Lee M.R.F., (2019). Modelling the diurnality of N<sub>2</sub>O emissions on the North Wyke Farm Platform. 7<sup>th</sup> CNC, Harpenden, 2019.</li>
<li class="ml-6 p-3">Harris P., Darch T., Lee M.R.F. (2019). Mineral geospatial variation across a typical pasture field. Minerals from Grassland, Harpenden, UK, 2019.</li>
<li class="ml-6 p-3">Jones A., Takahashi T., Fleming H., Griffith B., Harris P., Lee M., (2019). Using pre-weaning lamb liveweight as a predictor of carcass quality. British Society of Animal Science, Edinburgh, April 2019, pp 11.</li>
<li class="ml-6 p-3">Jones A., Takahashi T., Fleming H., Griffith B., Harris P., Lee M., (2019). Pre-weaning and post-weaning growth performances of lambs may be uncorrelated. British Society of Animal Science, Edinburgh, April 2019, pp 138.</li>
<li class="ml-6 p-3">Jones A.G., Takahashi T., Fleming H. Griffith B.A., Harris P, Lee M.R.F. (2019). Redefining key performance indicators for sheep production systems. European Federation of Animal Science, Ghent, Belgium, August 2019, pp 223.</li>
<li class="ml-6 p-3">Kao P-T., Darch T., McGrath S., Buss H., Warren H. Lee M.R.F. (2019). Micronutrient form and distribution in grazing pasture systems. EMG-AMG Research in Progress meeting, Bristol,UK, June 13<sup>th</sup> 2019.</li>
<li class="ml-6 p-3">Lee M.R.F., Takahashi T., McAuliffe G.A., Tichit M. (2019). Agricultural sustainability metrics based on land required for production of essential human nutrients. F-TALES: Challenges in reproductive medicine – Ghent Belgium, 17-18<sup>th</sup> September.</li>
<li class="ml-6 p-3">Lee M.R.F. (2019). Agricultural sustainability metrics based on land required for production of essential human nutrients. LASA Conference, Birmingham, 28th November 2019, pp 40.</li>
<li class="ml-6 p-3">McAullife G., Takahashi T., Harris P., Lee M., (2019). Effects of breeding-herd management strategies on carbon footprints of pasture-based beef production systems calculated using measured emission factors. British Society of Animal Science, Edinburgh, April 2019, pp 83.</li>
<li class="ml-6 p-3">McAuliffe G.A., Takahashi T., Lee M.R.F. (2019). Does choice of nutrients profiling rule affect relative environmental rankings of food products? European Federation of Animal Science, Ghent, Belgium, August 2019, pp 207.</li>
<li class="ml-6 p-3">McAuliffe G.A., Takahsahi T., Lee M.R.F. (2019). How much is enough – the effect of nutrient profiling on carbon footprints of 14 common food products. European Federation of Animal Science, Ghent, Belgium, August 2019, pp 425.</li>
<li class="ml-6 p-3">Pulley S., Collins A.L. (2019). Spatio-temporal patterns in fine sediment generation from fifteen grassland fields on the North Wyke Farm Platform. In session: Land degradation due to natural and anthropogenic drivers: impacts on runoff, soil erosion and sediment yield at multiple scales, 27<sup>th</sup><a class="text-blue-700 hover:text-yellow-700" href="http://www.iugg2019montreal.com/" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;"> IUGG General Assembly, Montreal, Canada, July 2019.</a></li>
<li class="ml-6 p-3">Pulley S., Collins A.L. (2019). The importance of timing of scheduled ploughing and reseeding operations for fine sediment generation from hydrologically- isolated grassland fields in the South West UK. <a class="text-blue-700 hover:text-yellow-700" href="https://www.teagasc.ie/publications/2019/catchment-science-2019.php" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">Catchment Science 2019: Achieving quality water in diverse and productive agricultural landscapes under a changing climate, Wexford, Ireland, November 2019.</a></li>
<li class="ml-6 p-3">Rivero M.J., Martin G.B., Cooke A. Lee M.R.F. (2019). What is an outlier telling us – hot summers might affect reproductive performance of sheep in autumn. European Federation of Animal Science, Ghent, Belgium, August 2019, pp 261.</li>
<li class="ml-6 p-3">Takahashi T., Harris P., Mcauliffe G.A., Jones G.A., Lee M.R.F. (2019). Low-resolution soil sampling may provide no useful information to grazing farms. European Federation of Animal Science, Ghent, Belgium, August 2019, pp 208.</li>
<li class="ml-6 p-3">Takahashi T., McAuliffe G.A., Lee M.R.F. (2019). Quantifying unintended macroeconomic consequences of meat taxation. European Federation of Animal Science, Ghent, Belgium, August 2019, pp 197.</li>
<li class="ml-6 p-3">Upadhayay H.R., Micale M., Zhang Y., Collins A.L. (2019). Integration of geochemical and isotopic biomarker tracers to apportion functionally similar sediment sources at catchment scale. <a class="text-blue-700 hover:text-yellow-700" href="https://www.teagasc.ie/publications/2019/catchment-science-2019.php" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">Catchment Science 2019: Achieving quality water in diverse and productive agricultural landscapes under a changing climate, Wexford, Ireland, November 2019.</a></li>
<li class="ml-6 p-3">Wu, L., (2019). Invited presentation: the impact of land use change on the nitrogen use efficiency, nitrogen and carbon budgets of agricultural systems with over 100 audiences from research organisations and higher education. The 2<sup>nd</sup> International Conference on Non-point Source Pollution Control and Aquatic Ecosystem Protection, Wuhan, China, 20<sup>th</sup>-23<sup>rd</sup> September 2019.</li>
<li class="ml-6 p-3">Wu, L.,(2019). Invited presentation: assess ecosystem services in grassland using a modelling approach combined with observations with over 100 audiences from universities, research organisations, consultancies and farmers. The 2019 international conference on organic agriculture and rural revitalisation, Beijing, China, 25<sup>th</sup>-26<sup>th</sup> September 2019.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2018</h3>
<ul>
<li class="ml-6 p-3">Cardenas L.M., Charteris A.F., Harris P., Marsden K.A., Harris I., Guo Z., Beaumont D.A., Taylor H., Sanfratello G., Jones D.L., Whelan M.J., Chadwick D.R., (2018). Exploring the spatial variability of N<sub>2</sub>O emissions from a grazed upland and lowland site. N workshop INRA, France 2018.</li>
<li class="ml-6 p-3">Elayadeth-Meethal M., Misselbrook T., Fleming H., Loick N. Rivero J. Lee M.R.F. (2018). Dynamics of methane and carbon dioxide emission in the UK grassland system. World Congress on Genetics Applied to Livestock Production (WCGALP). Auckland, New Zealand, 11-16<sup>th</sup> February 2018, pp 143.</li>
<li class="ml-6 p-3">Harris P., Darch T., Lu B., Comber A., Lee M.R.F., (2018). Investigation of the multivariate structure of a soils micronutrients data set at the farm-scale. Spatial Accuracy, Beijing 2018.</li>
<li class="ml-6 p-3">Harris P., Takahashi T., Griffith B., Hunt J., Hawkins J., Rivero J., Sint H., Lee M., (2018). The North Wyke Farm Platform. Association of Applied Biologist – Long Term Experiments Conference, Harpenden, 21<sup>st</sup> May 2018, pp 51.</li>
<li class="ml-6 p-3">Harris P., (2018). The North Wyke Farm Platform and other National Capabilities at Rothamsted Research Exploratory Workshop: Sustainable Agriculture, Upsalla, Sweden, 2018.</li>
<li class="ml-6 p-3">Hawkins, J.M.B., (2018). Invited Keynote: The North Wyke Farm Platform – Establishing and Managing a National Capability. 3<sup>rd</sup> International Workshop on High Temporal Resolution Water Quality Monitoring and Analysis, Cork, Ireland, 12-14<sup>th</sup> June 2018.</li>
<li class="ml-6 p-3">Lee, M.R.F, Takahashi T., McAuliffe G.A., Tichit M., (2018). Agricultural sustainability metrics based on land required for production of essential human nutrients. European Federation of Animal Science, Dubrovnik, Croatia, August 2018, pp 339.</li>
<li class="ml-6 p-3">Le Cocq K., McAuliffe G., Horrocks C., Darch T., Takahashi T., Blackwell M., Misselbrook T., Lee M.R.F., Cardenas L., (2018). Nutrient cycling in grassland systems: N, P and C cycling in a plot experiment on the North Wyke Farm Platform. 20<sup>th</sup> N Workshop, Rennes, France, 25-27<sup>th</sup> June 2018.</li>
<li class="ml-6 p-3">McAuliffe G., Takahashi T., White S., Hallett K., Lee M.R.F. (2018). Temporal change of fatty acid profiles in three pasture systems over two grazing seasons. British Society of Animal Science, pp 208.</li>
<li class="ml-6 p-3">McAuliffe G., Takahashi T., White S., Hallett K., Lee M.R.F. (2018). Effects of farm-scale grasslands management strategies on nutritional quality of pasture-reared beef. British Society of Animal Science, pp 72.</li>
<li class="ml-6 p-3">McFadzean J., Davies D.R., Hodgson C.J., Van Der Giezen M., Lee M.R.F., Dungait J.A.J. (2018). Spatial variation in baled silage quality and faecal origin microbes. British Society of Animal Science, pp 104.</li>
<li class="ml-6 p-3">McFadzean J., Le Cocq K., Brown B., Hodgson C., Davies D., Lee M.R.F., Van Der Giezen M., Dungait J. (2018). Aerobic spoilage of grass silage: Listeria and forage quality. International Silage Conference, pp 120-121.</li>
<li class="ml-6 p-3">Rivero, M.J., McAuliffe G.A., Takahashi T., Elayadeth-Meethal M., Misselbrook T., Coffey M., Wall, E., Harris P., Lee M.R.F., (2018). Steps for selecting cattle for sustainability traits on pasture based systems. World Congress on Genetics Applied to Livestock Production (WCGALP), Auckland, New Zealand, 11-16 <sup>th</sup> February 2018.</li>
<li class="ml-6 p-3">Sint, H, (2018). The North Wyke Farm Platform – Data Portal and Quality Control. 3<sup>rd</sup> International Workshop on High Temporal Resolution Water Quality Monitoring and Analysis, Cork, Ireland, 12-14<sup>th</sup> June 2018.</li>
<li class="ml-6 p-3">Takahashi T, Harris P, Cooke AS, Rivero MJ, Lee MRF, (2018). Improving the farm-scale livestock production efficiency through field-scale soil measurements. European Federation of Animal Science, Dubrovnik, Croatia, August 2018.</li>
<li class="ml-6 p-3">Takahashi T, Harris P, Cooke AS, Rivero MJ, Lee MRF, (2018). Evaluating field-level performance of rotational grazing systems based on high-resolution primary data. BSAS, Ireland.</li>
<li class="ml-6 p-3">Takahashi T, Rubio V, Mead A, Cardenas L, Glendining M, Lattanzi F, Macdonald A, Misselbrook T, Terra J, Lee M. (2018). Novel method to evaluate farming systems based on long-term data from field trials. Association of Applied Biologist – Long Term Experiments Conference, Harpenden, 21<sup>st</sup> May 2018, pp 50.</li>
<li class="ml-6 p-3">Thomas A., Bailey M., Finn A., Fleming H.R., Lee M.R.F., Mead A., Morales-Aza B., Vipond B., Eisler M.C. (2018). Live-attenuated vaccines as model viral infection systems: an approach from human medicine to investigate bovine respiratory disease. Veterinary Vaccinology Network Conference, University of Stirling, Scotland, 18-19<sup>th</sup> January 2018.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2017</h3>
<ul>
<li class="ml-6 p-3">Cardenas L., Takahashi T., Harris P., Mead A., Lee M., (2017). Redefining sustainability: novel metrics to evaluate farming systems based on the dynamic flow of nutrients. Aspects of Applied Biology, 136, pp 143-144 Sustainable Intensification, Harpenden, 28–30<sup>th</sup> November. 2017.</li>
<li class="ml-6 p-3">Curceac S., Atkinson P.M., Milne A., Wu L., Harris P., (2017). Spatio-temporal statistical analysis of measured and simulated fine-resolution datasets generated from the North Wyke Farm Platform.<a class="text-blue-700 hover:text-yellow-700" href="/sites/default/files/groups/North_Wyke_Farm_Platform_National_Capability/DataPortal/Stelian%20Curceac_Poster%20TIES-GRASPA%202017.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;"> Environmetrics 2017.</a></li>
<li class="ml-6 p-3">Curceac S., Atkinson P.M., Milne A., Wu L., Harris P., (2017). Exploratory analysis of measured and simulated fine-resolution spatio-temporal data sets generated from the North Wyke Farm Platform. Spatial Statistics 2017.</li>
<li class="ml-6 p-3">Eisler M.C., Lee M.R.F., Martin G.B., Ananth D., Chagunda M.G.G., Dungait J.A.J., Goddard E., Greathead H., Liu J., Lopez-Villalobos N., Mathew S., Montossi F., Mwakasungula S., Rice C.W., Tarlton J.F., Vinod V.K., Van Suan R., Winter M., Wright I. (2017). The global farm platform initiative – towards sustainable livestock systems. European Association of Animal Production. Tallinn, 28<sup>th</sup> August–1<sup>st</sup> September 2017, pp 421.</li>
<li class="ml-6 p-3">Harris P., Takahashi T., Lee M., (2017). Visualisation of uncertainty for the trade-off triangle used in sustainable agriculture. Geophysical Research Abstracts Vol 19. EGU, Vienna 2017.</li>
<li class="ml-6 p-3">Harris P., (2017). Open access research data generated from the North Wyke Farm Platform, European Space Agency workshop, Stoke Climsland, UK, 2017.</li>
<li class="ml-6 p-3">Harris P., (2017). Open access research data generated from the North Wyke Farm Platform, Jump Start Agritech, Penryn, UK, 2017.</li>
<li class="ml-6 p-3">Harris P., Takahashi T., Blackwell M., Cardenas L., Collins A., Dungait J., Eisler M., Hawkins J., Misselbrook T., McAuliffe G., McFadzean J., Murray P., Orr R., Rivero, J., Wu L., Lee M., (2017). A farm platform approach to optimizing temperate grazing-livestock systems: metrics for trade-off assessments and future innovations. EGU Vienna 2017.</li>
<li class="ml-6 p-3">Humphreys M.W., Collins R.P., Marshall A.H., Marley C.L., Walawee N.M., Doonan J.H., Dungait J.A.J., Harper J.A., Gasior D., Camargo-Rodriguez A., Murray P.J., (2017). Novel grasslands for agricultural production and flood mitigation. Proceedings of the 19<sup>th</sup> Symposium of the European Grassland Federation, Alghero, Italy, 7-10<sup>th</sup> May 2017 <a class="text-blue-700 hover:text-yellow-700" href="https://iris.unito.it/retrieve/handle/2318/1657936/383986/EGF2017-proceedingsFULL-rid.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">CNR-ISPAAM, Sassari, Ital, pp 570-572.</a></li>
<li class="ml-6 p-3">Lee M.R.F. (2017). Steps to sustainable ruminant livestock production. ASA, CSSA and SSSA International Meeting, Tampa, Florida, USA, 22<sup>nd</sup> – 25<sup>th</sup> October 2017, 40-1.</li>
<li class="ml-6 p-3">Matthews R., Blackwell M., Collins A., Harris P., Maltby E., Sint H., (2017). A novel tool to assess ecosystem services delivered by grassland systems. Sustainable Intensification, Harpenden, 28–30<sup>th</sup> November 2017.</li>
<li class="ml-6 p-3">McAuliffe G., Takahashi T., Orr R., Harris P., Richardson I. Lee M. (2017). Developing novel environmental metrics for beef production systems to account for differences in meat quality. Aspects of Applied Biology, 136, pp 144-145. Sustainable Intensification, Harpenden, 28–30<sup>th</sup> November 2017.</li>
<li class="ml-6 p-3">Takahashi T., Cardenas L.M., Harris P., Mead A., Lee M.R.F., (2017). Novel metrics to evaluate livestock farming systems based on dynamic flows of nutrients. European Association of Animal Production Tallinn, 28<sup>th</sup> August–1<sup>st</sup> September 2017, pp 212.</li>
<li class="ml-6 p-3">Takahashi T., Harris P., Orr R.J., Hawkins J.M.B., Rivero M.J., Lee M.R.F., (2017). Downscaling whole-farm measures of livestock production efficiency to the individual field level. European Association of Animal Production, Tallinn, 28<sup>th</sup> August–1<sup>st</sup> September 2017, pp 168.</li>
<li class="ml-6 p-3">Takahashi T, Lee M.R.F. (2017). Modelling the food-feed competition for agricultural land under heterogeneous soil fertility. British Society of Animal Science, pp 129.</li>
<li class="ml-6 p-3">Thomas A., Lee M.R.F., Bailey M., Finn A., Eisler M.C. (2017). Characterisation and development of the bovine respiratory microbiome. European Association of Animal Production. Tallinn, 28<sup>th</sup> August–1<sup>st</sup> September 2017, pp 323.</li>
<li class="ml-6 p-3">Thomas A., Lee M.R.F., Eisler M.C. (2017). Bacterial colonisation dynamics and development of the bovine respiratory microbiome. British Cattle Veterinary Association (BCVA) Congress, 19<sup>th</sup> – 21<sup>st</sup> October 2017.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2016</h3>
<ul>
<li class="ml-6 p-3">Cardenas L.M., Dunn R.M., Misselbrook T.H., Harris P., Orr R.J., Lee M.R.F., (2016). The North Wyke Farm Platform: the impact of ploughing, cultivations and reseeding on emissions of CO<sub>2</sub> and N<sub>2</sub>O. Proceedings of the 26<sup>th</sup> General Meeting of the European Grassland Federation,Trondheim, Norway, 4-8<sup>th</sup> September 2016. Paper 5.13, pp 161.</li>
<li class="ml-6 p-3">Dunn R.M., Boden J., Misselbrook T., Orr R.J., Griffith B., Neale J., Cardenas L.M., (2016). Greenhouse gas emissions from a reseeded grassland on the North Wyke Farm Platform. Steps to Sustainable Livestock, Bristol, UK, 12-15<sup>th</sup> January 2016.</li>
<li class="ml-6 p-3">Harris P., Griffith B., Sint H., Hawkins J., Collins A., Wu L., Cardenas L., Misselbrook T., Blackwell M., Dungait J., Murray P., Orr R.J., Lee M., (2016). Data mining the North Wyke Farm Platform data sets. <a class="text-blue-700 hover:text-yellow-700" href="/sites/default/files/groups/North_Wyke_Farm_Platform_National_Capability/DataPortal/Harris_Bristol_2016.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">Steps to Sustainable Livestock, Bristol, UK. 12-15 January 2016.</a></li>
<li class="ml-6 p-3">Harris P., Brunsdon C., Comber A., Sint H., Orr R., Lee M., Murray P., (2016). Modelling, interpreting and visualizing uncertainties for the North Wyke Farm Platform baseline field surveys. Spatial Accuracy 2016, Montpellier, France, 5-8<sup>th</sup> July 2016.</li>
<li class="ml-6 p-3">Harris P., Brunsdon C., Lee M., (2016). Visualizing uncertainties with the North Wyke Farm Platform data sets. EGU Vienna (2016), Geophysical Research Abstracts 18: EGU2016-17395.</li>
<li class="ml-6 p-3">Harris P., Howden N.J.K., Peukert S., Noacco V., Ramezani K., Tuominen E., Eludoyin A., Brazier R., Shepherd A., Griffith B., Orr R., Murray P., (2016). Contextualized geographically weighted principal components analysis for investigating baseline soils data on the North Wyke Farm Platform. In: Geostatistical and Geospatial Approaches for the Characterization of Natural Resources in the Environment. (Ed N.J. Raju) 16<sup>th</sup> Annual Conference of the International Association for Mathematical Geosciences, New Delhi, India, 17-20<sup>th</sup> October 2014, pp 651-655. <a class="text-blue-700 hover:text-yellow-700" href="http://www.springer.com/gb/book/9783319186627." onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;"><font color="#0066cc">http://www.springer.com/gb/book/9783319186627</font></a></li>
<li class="ml-6 p-3">Harris P., Sint H.M., Griffith B.A., Hawkins J.M.B., Evans J., Orr R.J., Lee M.R.F., (2016). The North Wyke Farm Platform: Data Portal. Proceedings of the 26<sup>th</sup> General Meeting of the European Grassland Federation, Trondheim, Norway, 4-8<sup>th</sup> September 2016. Paper 4.9, p 125.</li>
<li class="ml-6 p-3">Lee M.R.F, Harris P., McAuliffe G., Takahashi T., Cardenas L., Dungait J., Orr R., (2016). Is there a role for livestock in a low carbon future? LCGGES-2016.</li>
<li class="ml-6 p-3">Lee M.R.F., Darwent N. (2016). Grazing towards sustainability. Steps to Sustainable Livestock International Conference, Bristol, UK. 12– 15<sup>th</sup> January 2016, pp 7.</li>
<li class="ml-6 p-3">Lee M.R.F., Eisler M.C. (2016). Steps to sustainable livestock – The global farm platform. British Society of Animal Science, pp 170.</li>
<li class="ml-6 p-3">McAuliffe G.A., Takahashi T., Eisler M., Harris P., Orr R.J., Lee M.R.F., (2016). Carbon footprint analysis of pasture-based beef production systems based on rich primary data at the North Wyke Farm Platform in Devon, UK. 10<sup>th</sup> International Conference on Life Cycle Assessment of Food, Dublin, Ireland, 19<sup>th</sup>-21<sup>st</sup> October 2016.</li>
<li class="ml-6 p-3">McFadzean J., Koge J., Birnholz C., Paul B. K., Notenbaert A., Van Der Giezen M., Lee M.R.F., Dungait J. (2016). Developing tools to quantify sustainability of intensive and extensive ruminant farming systems in Sub-Saharan East Africa. Steps to Sustainable Livestock International Conference, Bristol, UK 12– 15<sup>th</sup> January 2016, pp 50.</li>
<li class="ml-6 p-3">MacFadzean J., Lee M.R.F., Dungait J. (2016). Developing tools to quantify sustainability of intensive and extensive ruminant farming systems in sub-Saharan east Africa. British Society of Animal Science, pp 59.</li>
<li class="ml-6 p-3">Roffet-Salque M., Lee M.R.F., Evershed R.P. (2016). Impact of modern cattle feeding practices on milk fatty acid stable carbon isotope compositions emphasise the need for caution in selecting reference animal tissues and products for archaeological investigations. International Symposium on Biomolecular Archaeology, Oxford, 14– 16<sup>th</sup> September 2016, pp 56.</li>
<li class="ml-6 p-3">Takahashi T., Lee M.R.F. (2016). Beyond ad hoc debates: a general equilibrium model incorporating the food–feed competition for agricultural land. International Rangeland Congress, Alberta, pp 358-360.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2015</h3>
<ul>
<li class="ml-6 p-3">Cardenas L.M., Dunn R., Misselbrook T., Orr R., Griffith B., Velazquez A., Burak E., Chen K., Harris P., Shepherd A., Repullo M., Collins A., (2015). Capturing the spatial variability of N<sub>2</sub>O emissions on grazed grassland. Synergy in Science: Partnering Solutions, Minneapolis, 2015.</li>
<li class="ml-6 p-3">Cardenas L., Chadwick D., Misselbrook T., Donovan N., Dunn R., Griffith B., Orr R., Smith K., Rees R., Bell M., Watson C., Mcgeough K., Mcneill G., Williams J., Cloy J., Thorman R., Dhanoa M., (2015). Heterogeneity of gaseous emissions in soils-spatial vs temporal variability. EGU General Assembly,Vienna, Austria. 12-17<sup>th</sup> April 2015. Paper 13863.</li>
<li class="ml-6 p-3">Harris P., Dungait J., Griffith B., Shepherd A., Sint H., Blackwell M., Cardenas L., Collins A., Lee M., Orr R.J., (2015). The North Wyke Farm Platform, a UK national capability for research into sustainability of temperate agricultural grassland management: progress and developments. EGU General Assembly,Vienna, Austria. 12 - 17<sup>th</sup> April 2015. Paper 15883.</li>
<li class="ml-6 p-3">Harris P, (2015). Issues and difficulties in the setting up of the North Wyke Farm Platform sensor network, Sensors for Water Interest Group, 2015</li>
<li class="ml-6 p-3">Lee M.R.F., Rice C., Ashok B., Collier S., Dungait J., Jahn M., Liu J., Eisler M.C. (2015). Global farm platforms for sustainable ruminant livestock production. National Institutes of Bioscience Conference, Harpenden, UK, 15-16<sup>th</sup> June 2015, pp 27-28.</li>
<li class="ml-6 p-3">Lee M.R.F., Martin G., Walter A., Montossi F., Ashok B., Sanford G.R., Eisler M.C. (2015). Steps towards sustainable livestock – the balance between yield and impact. 3<sup>rd</sup> International Symposium on Integrated Crop-Livestock Systems, Brasilia, Brazil, 14-17<sup>th</sup> July 2015, pp 24.</li>
<li class="ml-6 p-3">Lee M.R.F., Martin G., Walter A., Montossi F., Ashok B., Sanford G.R., Eisler M.C. (2015). Steps towards sustainable livestock – the balance between yield and impact. 3<sup>rd</sup> International workshop on sustainable farming systems, Kochi, Kerala, India, 19-20<sup>th</sup> August 2015, pp 5.</li>
<li class="ml-6 p-3">Rice C., Ashok B., Collier S., Dungait J., Eisler M., Jahn M., Liu J., Lee M. (2015). Global farm platforms for sustainable ruminant livestock production. Climate Smart Agriculture Conference, Montpellier, France. Climate Smart Livestock, pp 184.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2014</h3>
<ul>
<li class="ml-6 p-3">Griffith B.A., Harris P., Shepherd A., Peukert S., Hawkins J.M.B., Eyles C., Whitmore A., Blackwell M.S.A., Brazier R.E., Cardenas L.M., Wu L., Dungait J.A.J., Collins A.L., Gurr S., Murray P.J., Goulding K.W., Orr R.J., (2014). The North Wyke Farm Platform, a UK national capability for research into sustainability of temperate agricultural grassland: Infrastructure and Instrumentation.<a class="text-blue-700 hover:text-yellow-700" href="/sites/default/files/groups/North_Wyke_Farm_Platform_National_Capability/DataPortal/GRIFFITH%20Bonn_poster_2014_final%20ver%202.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;"><font color="#0066cc"> Environmental Observatories (Tereno) International Conference, Bonn, 29<sup>th</sup> September – 2<sup>nd</sup> October 2014.</font> </a></li>
<li class="ml-6 p-3">Harris P, Griffith BA, Shepherd A, Peukert S, Hawkins JMB, Eyles C, Whitmore A, Blackwell MSA, Brazier RE, Cardenas LM, Wu L, Dungait JAJ, Collins AL, Gurr S, Murray PJ, Goulding KW, Orr RJ, (2014). The North Wyke Farm Platform, a national capability for research into sustainability of temperate agricultural grassland management: data and modelling opportunities. Terrestrial Environmental Observatories (Tereno) International Conference, Bonn, 29<sup>th</sup> September – 2<sup>nd</sup> October 2014.</li>
<li class="ml-6 p-3">Lee M.R.F., Fleming H.R., Chen B., Corns W. (2014). Selenium speciation in ruminant feed using liquid chromatography hydride generation atomic fluorescence spectrometry (HPLC-HG-AFS). BNASS/Tracespec Conference, Aberdeen, 31<sup>st</sup> August – 4<sup>th</sup> September 2015.</li>
<li class="ml-6 p-3">Lee M.R.F., Martin G.B., Tarlton J.F., Eisler M.C. (2014). Towards sustainable and responsible production of livestock. European Association of Animal Production, Copenhagen, Denmark, pp 278.</li>
<li class="ml-6 p-3">Martin G.B., Rosales Nieto C., Lee M.R.F., Tarlton J.F., Eisler, M.C. (2014). Industria ganadera – Puede ayudar a alimentar al mundo sin destruir el pleneta. 7<sup>th</sup> Curso Internacional – Innovaciones en Reproduccion Animal, pp 7-20.</li>
<li class="ml-6 p-3">Misselbrook T., Harris P., Griffith B., Orr R.J., (2014). The North Wyke Farm Platform: Opportunities for the LiveM network. <a class="text-blue-700 hover:text-yellow-700" href="/sites/default/files/groups/North_Wyke_Farm_Platform_National_Capability/DataPortal/MISSELBROOK%20Bilbao%20FP%20poster.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">International Livestock Modelling and Research Colloquium, Bilbao, Spain, 14-16<sup>th</sup> October 2014.</a></li>
<li class="ml-6 p-3">Shepherd A., Orr R.J., Harris P., Griffith B.A., Murray P.J., (2014). Applications of spatial modelling and UAVs to pasture agri-research on the North Wyke Farm Platform. In: New sensors for a changing world. Remote Sensing and Photogrammetry Society, Aberystwyth, Wales, September 2014, p 169.</li>
<li class="ml-6 p-3">Shepherd A., Harris P., Orr R.J., Griffith B., Murray P., (2014). Applications of high resolution remote sensing with spatial modelling for sustainable grassland agriculture. 16<sup>th</sup> Annual Conference of the International Association for Mathematical Geosciences, New Delhi, India. 17-20<sup>th</sup> October 2014.</li>
<li class="ml-6 p-3">Thompson J.B., Orr R.J., Dungait J., Murray P.J., Lee M.R.F., (2014). Beef productivity on the North Wyke Farm Platform in two baseline years. <a class="text-blue-700 hover:text-yellow-700" href="/sites/default/files/groups/North_Wyke_Farm_Platform_National_Capability/DataPortal/THOMPSON%20PhD%20Symposium%20Poster%202014.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">Grassland Science in Europe, Vol. 19 – EGF at 50: the Future of European Grasslands, p 644-646.</a></li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">​2013</h3>
<ul>
<li class="ml-6 p-3">Griffith B.A., Hawkins J.M.B., Orr R.J., Blackwell M.S.A., Murray P.J., (2013). The North Wyke Farm Platform: methodologies used in the remote sensing of the quantity and quality of drainage water. Water resources and catchment management in grassland and forage systems. 22<sup>nd</sup> International Grasslands Congress,Sydney, Australia, 15–19<sup>th</sup> September 2013, pp 1453-1455.</li>
<li class="ml-6 p-3">Lee M., Murray P., Eisler M. (2013). A temperate grassland farm platform – North Wyke. In: Global Food Security and Future Livestock Farms in Varied Climates. [Eds: G.S.L.H.V. Prasada Rao, S. Ramkumar, G. Girish Varma]. Kerala Veterinary and Animal Science University, Wayanad, India, pp 8-12.</li>
<li class="ml-6 p-3">Murray P.J., Griffith B.A., Orr R.J., Peukert S., Shepherd .A, (2013). The North Wyke Farm Platform - A new National Capability for investigating sustainable intensification of livestock production. Sustainable intensification: The pathway to low carbon farming? SRUC, Edinburgh. 25-27<sup>th</sup> September 2013, pp 179-180.</li>
<li class="ml-6 p-3">Murray P.J., Griffith B.A., Orr R.J., Shepherd A., Blackwell M.S.A., Hawkins J.M.B., Peukert S., (2013). The North Wyke Farm Platform: A new UK national capability for research into sustainability of agricultural temperate grassland management. Water resources and catchment management in grassland and forage systems. 22<sup>nd</sup> International Grasslands Congress, Sydney, Australia, 15-19<sup>th</sup> September 2013, pp 1931-1933.</li>
<li class="ml-6 p-3">Murray P.J., Griffith B., Orr R.J., Peukert S., Shepherd A., (2013). The North Wyke Farm Platform: a new UK national capability for research into sustainable grassland production. In: Accurate and efficient use of nutrients on farms. (Eds L.D. Currie and C L. Christensen). Occasional Report No. 26. Fertilizer and Lime Research Centre, Massey University, Palmerston North, New Zealand.</li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2012</h3>
<ul>
<li class="ml-6 p-3">Ahmed K.D., Murray P.J., Blackshaw R., (2012). Systematic sampling of agricultural grassland to investigate the spatial distribution of soil insects. In: Ento’12, Royal Entomological Society Annual Meeting, Anglia Ruskin University, Cambridge, 18-20<sup>th</sup> July 2010.</li>
<li class="ml-6 p-3">Eludoyin A.O., Brazier R., Quine T., Bol R., Orr R.J., Griffith B., (2012). Improved understanding of solute concentration-discharge dynamics through state-of-the-art antecedent moisture content (AMC) monitoring and analysis. Geophysical Research Abstracts, EGU General Assembly, Vienna, Austria, April 2012, pp 1060.</li>
<li class="ml-6 p-3">Eludoyin A.O., Brazier R., Quine T., Murray P.J., (2012). Relationship between solute hysteretic behaviour and hydrological pathways at farm-scale. <a class="text-blue-700 hover:text-yellow-700" href="/sites/default/files/groups/North_Wyke_Farm_Platform_National_Capability/DataPortal/Bayo%20poster%20Aberdeen%202012%20with%20updated%20RRES%20logo%20Mar%2015.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;"><font color="#0066cc">Aberdeen 2012.</font></a></li>
</ul>
<h3 class="m-5 border border-green-950 rounded bg-slate-300 p-5 w-auto text-xl text-pretty">2011</h3>
<ul>
<li class="ml-6 p-3">Hatch D.J., Murray P.J., Orr R.J., Griffith B.A., (2011). The North Wyke Farm Platform: A UK national capability for agri-environmental research. In: Agricultural Ecology Research: Its role in delivering sustainable farm systems. Aspects of Applied Biology 109, pp 115-118.</li>
<li class="ml-6 p-3">Hodgson C.J., Murray P.J., Hatch D.J., (2011). The North Wyke Farm Platform: an opportunity for determining pathogen survival and transfers of pathogenic species from whole farm livestock systems. In: Faecal Indicators - Problem or Solution? Edinburgh, 6-8<sup>th</sup> June 2011.</li>
<li class="ml-6 p-3">Orr R.J., Griffith B.A., Rose S., Hatch D.J., Hawkins J.M.B., Murray P.J., (2011). Designing and creating the North Wyke Farm Platform. Catchment Science, Dublin, Ireland, 14-16 September 2011, p 35.</li>
<li class="ml-6 p-3">Peukert S., Bol R., Dixon E., Brazier R., (2011) Field-scale spatial isotope (δ13C and δ15N) variability in the surface of an intensively managed grassland. <a class="text-blue-700 hover:text-yellow-700" href="/sites/default/files/groups/North_Wyke_Farm_Platform_National_Capability/DataPortal/PEUKERT%20SIMSUG%20poster%20with%20updated%20RRES%20logo%20Mar%2015.pdf" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">Stable Isotope Mass Spectrometry User Group Meeting, Lancaster Environment Centre, 23-24<sup>th</sup> November.</a></li>
<li class="ml-6 p-3">Peukert S., Bol R., Quine T., Brazier R., (2011). Impacts of farm-scale grassland management on water quality. International Association for Sediment Water Science (IASWS) Symposium, Dartington, UK, June 2011.</li>
</ul>
<pre>

</pre>
<li>
    <h3 class="m-0 border border-green-950 bg-slate-400 p-5 w-auto text-xl text-pretty">Reports and Pre-prints</h3>
</li>

<ul>
<li class="ml-6 p-3"> Sharma S., Sharma S., Neal A., Malvar S., Rodrigues E., Crawford J., Kiciman E. and Chandra R. (2022). Causal Modeling of Soil Processes for Improved Generalization. <a class="text-blue-700 hover:text-yellow-700" href="https://doi.org/10.48550/arXiv.2211.05675" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">https://doi.org/10.48550/arXiv.2211.05675</a>.</li>
<li class="ml-6 p-3">Jordan, P., Cassidy, R. (2020). An evaluation of enhanced water quality monitoring methods for Northern Ireland. Report from Project 17/4/07 DAERA directed Agri-Food and Biosciences Institute (AFBI) Research Work Programme 2017/18 “An evaluation of water quality monitoring options suitable for implementation in Northern Irish river catchments”.</li>
<li class="ml-6 p-3">Granger, S. J., Quincke, J. A., Harris, P., Collins, A. L. and Blackwell, M. S. (2018). Comparison of high frequency, in-situ water quality analysers and sensors with conventional water sample collection and laboratory analyses: phosphorus and nitrogen species. Hydrol. Earth Syst. Sci. Discuss.,  2018,  1-33. (<a class="text-blue-700 hover:text-yellow-700" href="https://hess.copernicus.org/preprints/hess-2017-684/" onclick="window.open(this.href, '', 'resizable=yes,status=no,location=yes,toolbar=no,menubar=yes,fullscreen=no,scrollbars=yes,dependent=no'); return false;">doi: 10.5194/hess-2017-684</a>)</li>
</ul>


</x-guest-layout>
